//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDYCMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralMaterials
    {
        public int ContainerID { get; set; }
        public string HTML { get; set; }
        public bool isHidden { get; set; }
    }
}
